stages:
    - build
    - test
#    - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

# build:
#   stage: build
#   image: docker:20.10.16
#   services:
#   - docker:20.10.16-dind
#   before_script:    
#     - docker info
#     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
#   script:
#     - docker build -t $TAG_COMMIT -t $TAG_LATEST .
#     - docker push $TAG_COMMIT
#     - docker push $TAG_LATEST

test:
  stage: test
  image: docker:20.10.16-dind
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker run --rm 'registry.gitlab.com/taylor.f/biostar-central/master:latest' ls
